# Generated by Django 3.0 on 2022-06-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_product_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile_No', models.ImageField(upload_to='')),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
    ]
